### ISSUE TITLE
Cleanup //  "grunt webpack" task warns about "babel-register"

### ISSUE THREAD

**Issue by slurmulon** [AngularClass/NG6-starter#132]
If you clone the repo, install all of the globals and then run:

```
$ gulp webpack
[09:37:31] Failed to load external module babel-register
[09:37:31] Requiring external module babel-core/register
[09:37:32] Using gulpfile ~/Code/clint/ui/gulpfile.babel.js
[09:37:32] Starting 'webpack'...
```

The build continues and is ultimately successful, but we see a sketchy warning: `Failed to load external module babel-register`. Haven't had the time to look into it yet, but perhaps a version upgrade of `babel-core` would solve the issue.

**Comment by slurmulon** [comment]
Just as a convenience, here is a list of potential upgrades throughout the package:

```
$ ncu
 normalize.css          ^3.0.3  →   ^4.1.1
 babel-core             ^5.4.2  →   ^6.7.6
 babel-loader           ^5.0.0  →   ^6.2.4
 css-loader            ^0.19.0  →  ^0.23.1
 gulp-template          ^3.0.0  →   ^4.0.0
 html-webpack-plugin    ^1.7.0  →  ^2.15.0
 karma-mocha-reporter   ^1.0.2  →   ^2.0.0
 ng-annotate-loader     0.0.10  →    0.1.0
 node-libs-browser      ^0.5.0  →   ^1.0.0
 style-loader          ^0.12.2  →  ^0.13.1
 stylus-loader          ^1.1.1  →   ^2.0.0
 yargs                  ^3.9.0  →   ^4.6.0
```

**Comment by slurmulon** [comment]
Upgrading all packages to the latest (perhaps unsurprisingly) causes critical issues:

```
$ gulp webpack
[09:55:31] Requiring external module babel-register
/Users/adminaccount/Code/clint/ui/gulpfile.babel.js:3
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at loader (/Users/adminaccount/Code/clint/ui/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adminaccount/Code/clint/ui/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
```

**Comment by bora89** [comment]
@slurmulon I am having that too. Looking for the solution too

**Comment by zysam** [comment]
+1

**Comment by madflow** [comment]
@bora89 I was able to come by this by introducing a ```.babelrc``` file with:

```{
  "presets": ["es2015"]
}```

and adding extra dependencies:

```
npm install babel-preset-es2015 --save-dev
npm install babel-register --save-dev
npm install --save-dev run-sequence
npm install --save-dev del
```

**Comment by bora89** [comment]
@madflow thank you for the reply, but I am afraid that will work only with Babel 6.x. Did you update it safely?

**Comment by madflow** [comment]
Yes - it is for Babel 6. Sorry - I came to this repo for inspiration for a current project. I just started with what npm gave me. I can not comment on if it is save to update this specific "Starter Seed" - but I have no indication that you should not use angular+webpack+babel 6.x.

**Comment by oric01** [comment]
@madflow I did the same as you with ncu, babel 6 etc... I confirm that it works (after a couple of search... :) ) as you mentionned for the main part.
I still have some stylus alert to fix (on webpack script) but for now the NG6 starter seed works as before.
