### ISSUE TITLE
Errors I can't handle

### ISSUE THREAD

**Issue by ivanberry** [AngularClass/NG6-starter#169]
Once I run the gulp , It will change the PWD to E:( yeah , my OS is window 7), below I will post the error message:

``` bash
$ gulp
[08:58:23] Working directory changed to E:\
module.js:341
    throw err;
    ^

Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\gulpfile.js:5:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

```

yeah, I noticed the missing module, so I do this:

``` bash
npm install del --save-dev
```

and also change the working directory to E:\ ，and run it again, Yes , I have module _del_ now, but there is another missing!

so, I miss something?
- cd the NG6-starter directory
- npm install
- gulp watch

Thanks!

**Comment by ivanberry** [comment]
I have try something, and it seems fix it, but I dont why exactly.

- npm rm -g gulp
- npm install -g gulp-cli
update the gulp globally

- npm install gulp@3.8.11 --save
update the gulp globally

- gulp --gulpfile gulpfile-babel.js

why my gulp dont load the *gulpfile.babel.js* under NG6, but changed the directory up to *e:\*, so I use the *gulp --gulpfile* to hack this.

Yeah, the gulp task runs and I can do my leainging on Angular . Thanks!

**Comment by fesor** [comment]
Closing this.
