### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by mydearxym** [AngularClass/NG6-starter#35]
```js
➜ NG6-starter-master git:(master) ✗ gulp
[00:59:25] Requiring external module babel-core/register
[00:59:25] Using gulpfile ~/code/react_playground/func-pl/NG6-starter-master/gulpfile.babel.js
[00:59:25] Starting 'default'...
[00:59:25] Starting 'webpack'...
[00:59:29] Version: webpack 1.12.2
        Asset     Size  Chunks             Chunk Names
    bundle.js   1.3 MB       0  [emitted]  main
bundle.js.map  1.51 MB       0  [emitted]  main
[00:59:29] Finished 'webpack' after 3.32 s
[00:59:29] Starting 'serve'...
[00:59:29] Finished 'serve' after 133 ms
[00:59:29] Starting 'watch'...
[00:59:29] Finished 'watch' after 17 ms
[00:59:29] Finished 'default' after 3.47 s

module.js:340
    throw err;
    ^
Error: Cannot find module 'connect-history-api-fallback'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at startServer (/Users/xieyiming/code/react_playground/func-pl/NG6-starter-master/node_modules/browser-sync/node_modules/browser-sync-ui/lib/server.js:70:13)
    at Object.module.exports.startServer [as fn] (/Users/xieyiming/code/react_playground/func-pl/NG6-starter-master/node_modules/browser-sync/node_modules/browser-sync-ui/lib/async.js:91:41)
    at /Users/xieyiming/code/react_playground/func-pl/NG6-starter-master/node_modules/browser-sync/node_modules/browser-sync-ui/lib/UI.js:184:14
    at iterate (/Users/xieyiming/code/react_playground/func-pl/NG6-starter-master/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
    at /Users/xieyiming/code/react_playground/func-pl/NG6-starter-master/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
    at /Users/xieyiming/code/react_playground/func-pl/NG6-starter-master/node_modules/browser-sync/node_modules/browser-sync-ui/lib/UI.js:192:13


```

**Comment by fesor** [comment]
@mydearxym can I close this issue?

**Comment by mydearxym** [comment]
@fesor  yes , thanks !
