### ISSUE TITLE
Cannot Find module 'dateformat'

### ISSUE THREAD

**Issue by adyngom** [AngularClass/NG6-starter#68]
Off a fresh install - running gulp outputs:
```
Error: Cannot find module 'dateformat'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/index.js:5:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

Anything I'm missing here

**Comment by fesor** [comment]
try to reinstall modules.

**Comment by adyngom** [comment]
Hmm I just realized that the project was mistakenly cloned inside another existing angular project I was working. I removed it and placed it at the root level of my Development folder. I still went ahead and removed and reinstalled the node_modules/. Seems to work perfectly. Thanks for the prompt response and thank you for putting this awesome starter together. Cheers
