### ISSUE TITLE
Not able to install Dependencies

### ISSUE THREAD

**Issue by strangfeld** [AngularClass/NG6-starter#76]
I followed the [Getting Started](https://github.com/AngularClass/NG6-starter/tree/jspm#user-content-getting-started) Guide of the JSPM Branch, but I'm not able get the project running, since `npm i` is failing every time.

I get following error with a socket.io dependency:
````
warn github:socketio/socket.io-client@1.3.7 dependency installs skipped as it's a GitHub package with no registry property set.
     If the dependencies aren't needed ignore this message. Alternatively set a registry or dependencies override or use the npm registry version at jspm install npm:socket.io-client@^1.3.7 instead.
````
and also with the tty-browserify package:
````
Looking up npm:tty-browserify

warn Error on download for github:jspm/nodelibs-tty
     Error: getaddrinfo ENOTFOUND
         at errnoException (dns.js:37:11)
         at Object.onanswer [as oncomplete] (dns.js:124:16)

warn Error on download for github:jspm/nodelibs-net
     Error: getaddrinfo ENOTFOUND
         at errnoException (dns.js:37:11)
         at Object.onanswer [as oncomplete] (dns.js:124:16)

err  Error downloading github:jspm/nodelibs-tty.
```` 

I tried to reinstall with cleared caches (`npm cache clear` and `jspm cc`), but this didn't help.

Edit: Github credentials are configured via `jspm registry config github`.
Edit2: OSX 10.11, JSPM v0.16.17, Node.js v0.10.33, NPM v3.3.5.

**Comment by strangfeld** [comment]
I updated to Node.js v4.0.0 and now `jspm install` passes without error.
